home_page:
  path: /{_locale}/home
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

boutique_page:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

rayon_page:
  path: /{_locale}/boutique/rayon/{idCategorie}
  controller: App\Controller\BoutiqueController::rayon
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

panier_page:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

panier_ajouter:
  path: /{_locale}/panier/ajout/{idProduit}
  controller: App\Controller\PanierController::ajoutPanier
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

panier_enlever:
  path: /{_locale}/panier/remove/one/{idProduit}
  controller: App\Controller\PanierController::panierEnlever
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'


panier_supprimer:
  path: /{_locale}/panier/remove/all/{idProduit}
  controller: App\Controller\PanierController::panierSupprimer
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

panier_validation:
  path: /{_locale}/panier/{idUser}
  controller: App\Controller\PanierController::panierToCommande
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

contact_page:
  path: /{_locale}/contact
  controller: App\Controller\BoutiqueController::contact
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

search:
  path: /{_locale}/recherche
  controller: App\Controller\BoutiqueController::search
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'



user_accueil:
  path: /{_locale}/accueil-utilisateur
  controller: App\Controller\UserController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

user_inscription:
  path: /{_locale}/inscription
  controller: App\Controller\UserController::new
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'
