home_page:
  path: /{_locale}/home
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

boutique_page:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

rayon_page:
  path: /{_locale}/boutique/rayon/{idCategorie}
  controller: App\Controller\BoutiqueController::rayon
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

panier_page:
  path: /{_locale}/panier
  controller: App\Controller\PanierController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

ajout_produit:
  path: /{_locale}/panier/ajout/{idProduit}
  controller: App\Controller\PanierController::ajoutPanier
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

contact_page:
  path: /{_locale}/contact
  controller: App\Controller\BoutiqueController::contact
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: 'fr'

test_page:
  path: /{_locale}/test